.sync/rust-toolchain.toml: Update cargo-deny to v0.18 (#59)
Update to version 0.18 to pick up the fix for the following issue:

https://github.com/EmbarkStudios/cargo-deny/issues/804

In the v0.18.6 release of cargo-deny:

https://github.com/EmbarkStudios/cargo-deny/releases/tag/0.18.6

---

Fixes this issue observed in patina-dxe-core-qemu:

```
Error: -20 00:22:52 [ERROR] failed to load advisory database: parse error: error parsing /home/runner/.cargo/advisory-dbs/github.com-9b36585d9d99f7b3/crates/cap-primitives/RUSTSEC-2024-0445.md: parse error: TOML parse error at line 8, column 8
  |
8 | cvss = "CVSS:4.0/AV:N/AC:L/AT:P/PR:L/UI:N/VC:L/VI:L/VA:L/SC:N/SI:N/SA:N"
  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
unsupported CVSS version: 4.0
```

Signed-off-by: Michael Kubacki <michael.kubacki@microsoft.com>